# Generated by Django 5.2 on 2026-08-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='路径名称')),
                ('color', models.CharField(default='#e6194b', max_length=20, verbose_name='显示颜色')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='顺序号')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='轨迹点说明')),
                ('status', models.CharField(choices=[('carrier', '已取'), ('notget', '未取')], default='notget', max_length=20, verbose_name='状态')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='mapapp.path')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('path', 'seq')},
            },
        ),
    ]
