# Generated by Django 5.2 on 2026-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='items',
            field=models.JSONField(blank=True, default=list, verbose_name='物品名称列表'),
        ),
        migrations.AddField(
            model_name='path',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='人物名称'),
        ),
        migrations.AddField(
            model_name='path',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='取得物品日期'),
        ),
    ]
