# Generated by Django 5.2 on 2026-08-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_path_items_path_person_name_path_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='items',
        ),
        migrations.RemoveField(
            model_name='path',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='path',
            name='pickup_date',
        ),
    ]
